### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by Olivier-tl** [alsauve/scaleogram#5]
Hi, the tests fail with an exception in matplotlib. Any attempt to plot a scaleogram will fail with the same error. I have the latest version of matplotlib & pywavelet on python 3.8 & Ubuntu. Any ideas?

```
python3 -m scaleogram.test

/usr/lib/python3.8/runpy.py:126: RuntimeWarning: 'scaleogram.test' found in sys.modules after import of package 'scaleogram', but prior to execution of 'scaleogram.test'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Multi-purpose test demo (needs graphic output for matplotlib)
  Plot cmor1-1.5 wavelet in time and frequency domains
  Plot scaleogram of a gaussian
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/olivier/.local/lib/python3.8/site-packages/scaleogram/test.py", line 113, in <module>
    test_cws()
  File "/home/olivier/.local/lib/python3.8/site-packages/scaleogram/test.py", line 42, in test_cws
    ax = cws(cwt,
  File "/home/olivier/.local/lib/python3.8/site-packages/scaleogram/cws.py", line 264, in cws
    ax.fill_between(xmesh, yborder, ymask, **coikw )
  File "/home/olivier/.local/lib/python3.8/site-packages/matplotlib/__init__.py", line 1565, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/olivier/.local/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 5218, in fill_between
    collection = mcoll.PolyCollection(polys, **kwargs)
  File "/home/olivier/.local/lib/python3.8/site-packages/matplotlib/collections.py", line 1073, in __init__
    Collection.__init__(self, **kwargs)
  File "/home/olivier/.local/lib/python3.8/site-packages/matplotlib/collections.py", line 164, in __init__
    self.update(kwargs)
  File "/home/olivier/.local/lib/python3.8/site-packages/matplotlib/artist.py", line 1006, in update
    ret = [_update_property(self, k, v) for k, v in props.items()]
  File "/home/olivier/.local/lib/python3.8/site-packages/matplotlib/artist.py", line 1006, in <listcomp>
    ret = [_update_property(self, k, v) for k, v in props.items()]
  File "/home/olivier/.local/lib/python3.8/site-packages/matplotlib/artist.py", line 1003, in _update_property
    return func(v)
  File "/home/olivier/.local/lib/python3.8/site-packages/matplotlib/collections.py", line 772, in set_alpha
    super().set_alpha(alpha)
  File "/home/olivier/.local/lib/python3.8/site-packages/matplotlib/artist.py", line 932, in set_alpha
    raise TypeError('alpha must be a float or None')
TypeError: alpha must be a float or None
```

**Comment by Olivier-tl** [comment]
See : #6
